<?php

/**
 * BaseMouvementAutomatique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $compte_id
 * @property boolean $actif
 * @property string $libelle
 * @property integer $numero_jour
 * @property string $credit
 * @property string $debit
 * @property Compte $Compte
 * 
 * @method integer              getCompteId()    Returns the current record's "compte_id" value
 * @method boolean              getActif()       Returns the current record's "actif" value
 * @method string               getLibelle()     Returns the current record's "libelle" value
 * @method integer              getNumeroJour()  Returns the current record's "numero_jour" value
 * @method string               getCredit()      Returns the current record's "credit" value
 * @method string               getDebit()       Returns the current record's "debit" value
 * @method Compte               getCompte()      Returns the current record's "Compte" value
 * @method MouvementAutomatique setCompteId()    Sets the current record's "compte_id" value
 * @method MouvementAutomatique setActif()       Sets the current record's "actif" value
 * @method MouvementAutomatique setLibelle()     Sets the current record's "libelle" value
 * @method MouvementAutomatique setNumeroJour()  Sets the current record's "numero_jour" value
 * @method MouvementAutomatique setCredit()      Sets the current record's "credit" value
 * @method MouvementAutomatique setDebit()       Sets the current record's "debit" value
 * @method MouvementAutomatique setCompte()      Sets the current record's "Compte" value
 * 
 * @package    Comptes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMouvementAutomatique extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mouvement_automatique');
        $this->hasColumn('compte_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('actif', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('numero_jour', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('credit', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('debit', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Compte', array(
             'local' => 'compte_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}