<?php

/**
 * BaseCompte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $solde_initial
 * @property Doctrine_Collection $Mouvements
 * @property Doctrine_Collection $MouvementsAutomatique
 * 
 * @method string              getNom()                   Returns the current record's "nom" value
 * @method string              getSoldeInitial()          Returns the current record's "solde_initial" value
 * @method Doctrine_Collection getMouvements()            Returns the current record's "Mouvements" collection
 * @method Doctrine_Collection getMouvementsAutomatique() Returns the current record's "MouvementsAutomatique" collection
 * @method Compte              setNom()                   Sets the current record's "nom" value
 * @method Compte              setSoldeInitial()          Sets the current record's "solde_initial" value
 * @method Compte              setMouvements()            Sets the current record's "Mouvements" collection
 * @method Compte              setMouvementsAutomatique() Sets the current record's "MouvementsAutomatique" collection
 * 
 * @package    Comptes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('compte');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('solde_initial', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mouvement as Mouvements', array(
             'local' => 'id',
             'foreign' => 'compte_id'));

        $this->hasMany('MouvementAutomatique as MouvementsAutomatique', array(
             'local' => 'id',
             'foreign' => 'compte_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}