<?php

/**
 * MouvementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MouvementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MouvementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mouvement');
    }
    
	public function retrieveMouvement(Doctrine_Query $q)
	{
	  return $this->addMouvementsQuery($q)->fetchOne();
	}

	public function getMouvements(Doctrine_Query $q = null)
	{
	  return $this->addMouvementsQuery($q)->execute();
	}

	public function countMouvements(Doctrine_Query $q = null)
	{
	  return $this->addMouvementsQuery($q)->count();
	}

	public function addMouvementsQuery(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('Mouvement m');
	  }

	  $alias = $q->getRootAlias();

	  $q->addOrderBy($alias . '.date DESC');

	  return $q;
	}
}