<?php

/**
 * MouvementAutomatique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Comptes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MouvementAutomatique extends BaseMouvementAutomatique
{
    
   /**
    * Retourne les mouvements automatiques d'un compte
    *
    * @return array
    * @access public
    */
    public function getMouvementAutomatiqueCompte() 
    {
    	//echo $this->getId();
    	$query = Doctrine_Query::create()
    		->from('MouvementAutomatique')
    		->where('compte_id = ?', $this->getId());

   		return $query->execute();
    }
}
