<?php

/**
 * MouvementAutomatiqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MouvementAutomatiqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MouvementAutomatiqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MouvementAutomatique');
    }
}