<?php

/**
 * Mouvement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Comptes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mouvement extends BaseMouvement
{   
   /**
    * 
    * Retourne le montant du compte courant
    */
	public function getCompteCourant()
    {
    	$query = Doctrine_Query::create()
    		->select('ROUND(SUM(credit),2) AS totalCreditTraite, ROUND(SUM(debit),2) AS totalDebitTraite')
    		->from('Mouvement')
    		->where('compte_id = ?', $this->getCompteId())
    		->andWhere('traite = 1');

   		return $query->execute();	
    }
    
   /**
    * 
    * Retourne le montant du compte prévisionnel
    */
	public function getComptePrevisionnel()
    {
    	$query = Doctrine_Query::create()
    		->select('ROUND(SUM(credit),2) AS totalCredit, ROUND(SUM(debit),2) AS totalDebit')
    		->from('Mouvement')
    		->where('compte_id = ?', $this->getCompteId());

   		return $query->execute();	
    }

   /**
    * Retourne si oui ou non le mouvement existe déjà sur le mois en cours du compte
    *
    * @param integer $compte_id
    * @param varchar $libelle
    * @param datetime $date
    * @param varchar $debit
    * @param varchar $mois
    * @param boolean $annee_suivante
    * @return boolean
    * @access public
    */
    public function getMouvementCompte($compte_id, $libelle, $numero_jour, $debit, $mois, $annee_suivante) 
    {
    	
    	if($mois == date('m'))
    	{
    		$date = date('Y').'-'.date('m').'-'.$numero_jour;
    	}
		
		//Si on veut afficher les prochains prelevements automatiques du mois suivant car on est à - de 9 jours du nouveau mois
    	if($mois == date('m')+1)
    	{
    		$date = date('Y').'-'.(date('m')+1).'-'.$numero_jour;
    	}
        	
        //Si on veut afficher les prochains prelevements automatiques du mois suivant spécifique janvier de l'année suivante car on est à - de 9 jours du nouveau mois
    	if($mois == "01" && $annee_suivante == TRUE)
    	{
    		$date = (date('Y')+1).'-01-'.$numero_jour;
    	}

    	//Si on veut afficher les prochains prelevements automatiques du mois en coute spécifique janvier car on est à - de 9 jours du nouveau mois
    	if($mois == "01" && $annee_suivante == FALSE)
    	{
    		$date = (date('Y')).'-01-'.$numero_jour;
    	}

    	$query = Doctrine_Query::create()
    		->from('Mouvement')
    		->where('compte_id = ?', $compte_id)
    		->andWhere('libelle = ?', $libelle)
    		->andWhere('date = ?', $date)
    		->andWhere('debit = ?', $debit);

    	if($query->count() > 0)
		{
			return true;
		}

		return false;
    }
}