<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/28 11:01:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=comptes',
  'username' => 'comptes',
  'password' => 'comptes',
  'name' => 'doctrine',
)),);
