<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/28 11:01:04
sfConfig::add(array(
  'mod_mouvement_automatique_enabled' => true,
  'mod_mouvement_automatique_view_class' => 'sfPHP',
));
