<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/28 11:01:04
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
