Compte:
  actAs: { Timestampable: ~ }
  columns:
    nom:           { type: string(255), notnull: true, unique: true }
    solde_initial: { type: string(255) }

Mouvement:
  actAs: { Timestampable: ~ }
  columns:
    compte_id:  { type: integer, notnull: true }
    traite:     { type: boolean }
    libelle:    { type: string(255), notnull: true }
    date:       { type: timestamp }
    credit:     { type: string(255) }
    debit:      { type: string(255) }
  relations:
    Compte: 
      alias: Compte
      foreignType: many
      onDelete: cascade
      local: compte_id 
      foreign: id
      foreignAlias: Mouvements

MouvementAutomatique:
  actAs: { Timestampable: ~ }
  columns:
    compte_id:    { type: integer, notnull: true }
    actif:        { type: boolean }
    libelle:      { type: string(255), notnull: true }
    numero_jour:  { type: integer(2) }
    credit:       { type: string(255) }
    debit:        { type: string(255) }
  relations:
    Compte: 
      alias: Compte
      foreignType: many
      onDelete: cascade
      local: compte_id 
      foreign: id
      foreignAlias: MouvementsAutomatique